config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord

  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to sessions_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action  :initialize_picrure, only:[:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all.includes(:user)
  end

  def new
    if params[:back]
      @picture = current_user.pictures.new(get_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.new(get_params)
    if @picture.save 
      redirect_to pictures_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @picture.update(get_params)
      redirect_to pictures_path, notice:"編集しました"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @picture.destroy
      redirect_to pictures_path, notice:"削除しました"
    else
      render:edit
    end
  end

  def confirm
    @picture = current_user.pictures.new(get_params)
  end

  private
  def get_params
    params.require(:picture).permit(:title, :image, :image_cache, :content, :user_id)
  end

  def initialize_picrure
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id),notice: "ログインしました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash.now[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  def new
    @user = User.new
  end

  def create
    @user = User.new(get_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private 
  def get_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user_content?(content_user)
    if content_user == current_user
      true
    else
      false
    end
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <a class="header_logo">Facebook_Clone<a>
      <% if logged_in? %>
        <li class="header_content"><%= "名前 : #{current_user.name }"%></li>
        <li class="header_content"><%= link_to "Profile", user_path(current_user.id) %></li>
        <li class="header_content"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
      <% end %>
    </header>
    <%= yield %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{@picture.errors.count}件のエラーがあります。" %>
      </h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_title">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="picture_image image_size">
    <br>
    <%= form.label :image %><br>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %><br>
  </div>
  <div class="picture_content">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <%= form.submit %>
<% end %>
<br>
<%= link_to "一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<h3>以下の内容で、よろしいでしょうか</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.label :title %><br>
  <%= @picture.title %><br>

  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %><br>
  <%= form.label :content %><br>
  <%= @picture.content %><br>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <br>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <br>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集</h2>
<%= render 'form', picture: @picture %>

app/views/pictures/index.html.erb
<article>
  <h1>投稿一覧</h1>
  <div class="btn-square-soft">
    <%= link_to "新規作成", new_picture_path %>  
  </div>
  <div class="container">
    <% @pictures.each do |f| %>
      <ul class="row">
        <div class='image_size'>
          <li class="col-sm-12 row_title"><%= f.title %></li>
          <li class="col-sm-6 row_image"><%= image_tag f.image.url%></li>
          <li class="col-sm-6 row_content"><%= f.content %></li>
          <li class="col-sm-6 row_remark"><%= "作成者 : #{f.user.name}" %></li>
          <li class="col-sm-2 row_remark"><%= f.updated_at  %></li>
          <% if current_user_content?(f.user) %>
            <li class="col-sm-2 row_remark"><%= link_to "編集", edit_picture_path(f.id) %></li>
            <li class="col-sm-2 row_remark"><%= link_to "削除", picture_path(f.id) ,method: :delete, data:{confirm:"本当に削除しても良いですか？"} %></li>
          <% end  %>
        </div>
      </ul>
    <% end %>
  </div>
</article>

app/views/pictures/new.html.erb
<h2>作成</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <div class='image_size'>
    <%= image_tag @picture.image.url %>
  </div>
</p>
<%= link_to 'Edit', edit_feed_path(@picture) %>
<%= link_to 'Back', feeds_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<div class="btn-square-soft">
  <%= link_to "新規投稿" ,new_picture_path %>
</div>
<div class="btn-square-soft">
  <%= link_to "投稿一覧" ,pictures_path %>
</div>